include($ENV{VCPKG_ROOT}/triplets/x64-linux.cmake)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_DISABLE_COMPILER_TRACKING ON)

set(COMMON_RELEASE_SANITIZER_FLAGS "-g1 -fsanitize=thread -fno-omit-frame-pointer")

string(APPEND VCPKG_C_FLAGS " ${COMMON_RELEASE_SANITIZER_FLAGS}")
string(APPEND VCPKG_CXX_FLAGS " ${COMMON_RELEASE_SANITIZER_FLAGS}")
string(APPEND VCPKG_LINKER_FLAGS " ${COMMON_RELEASE_SANITIZER_FLAGS}")
